FROM node:latest

# Creating app directory
RUN mkdir -p /usr/src/client
WORKDIR /usr/src/client

COPY package.json .

RUN npm install

RUN npm install -g serve

COPY . .

RUN npm run build

CMD ["serve", "-s", "build", "-l", "3000"]

