version: "2.0"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.${ENV}
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
      - /usr/src/client/build
    depends_on:
      - server
  server:
    build: ./server
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
