// Alerts
export const ADD_ALERT = "ADD_ALERT";
export const REMOVE_ALERTS = "REMOVE_ALERTS";

// User Registration
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const ACCOUNT_ACTIVATE_SUCCESS = "ACCOUNT_ACTIVATE_SUCCESS";
export const ACCOUNT_ACTIVATE_FAILED = "ACCOUNT_ACTIVATE_FAILED";

// User Authentication
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAILED = "GOOGLE_AUTH_FAILED";
export const SEND_RESET_EMAIL_SUCCESS = "SEND_RESET_EMAIL_SUCCESS";
export const SEND_RESET_EMAIL_FAILED = "SEND_RESET_EMAIL_FAILED";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";

// User Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

// User Logout
export const USER_LOGOUT = "USER_LOGOUT";

// Categories
export const GET_CATEGORIES = "SET_CATEGORIES";
export const REMOVE_CATEGORIES = "REMOVE_CATEGORIES";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS";
export const REMOVE_CATEGORY_FAILED = "REMOVE_CATEGORY_FAILED";
export const SET_EDIT_CATEGORY = "SET_EDIT_CATEGORY";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAILED = "EDIT_CATEGORY_FAILED";

// Goals
export const GET_GOALS_SUCCESS = "GET_GOALS_SUCCESS";
export const GET_GOALS_FAILED = "GET_GOALS_FAILED";
export const ADD_GOAL_SUCCESS = "ADD_GOAL_SUCCESS";
export const ADD_GOAL_FAILED = "ADD_GOAL_FAILED";
export const REMOVE_GOAL_SUCCESS = "REMOVE_GOAL_SUCCESS";
export const REMOVE_GOAL_FAILED = "REMOVE_GOAL_FAILED";
export const SET_EDIT_GOAL = "SET_EDIT_GOAL";
export const EDIT_GOAL_SUCCESS = "EDIT_GOAL_SUCCESS";
export const EDIT_GOAL_FAILED = "EDIT_GOAL_FAILED";
export const COMPLETE_GOAL_SUCCESS = "COMPLETE_GOAL_SUCCESS";
export const COMPLETE_GOAL_FAILED = "COMPLETE_GOAL_FAILED";

// Profile
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";
export const UPDATE_NAME_SUCCESS = "UPDATE_NAME_SUCCESS";
export const UPDATE_NAME_FAILED = "UPDATE_NAME_FAILED";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAILED = "UPDATE_ROLE_FAILED";
export const UPDATE_EMAIL_PASS_SUCCESS = "UPDATE_EMAIL_PASS_SUCCESS";
export const UPDATE_EMAIL_PASS_FAILED = "UPDATE_EMAIL_PASS_FAILED";
